---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Post title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: date
  type: datetime
  label: Publish Date
  description: ''
  config:
    required: true
    date_format: ''
    time_format: 
    display_utc: false
    export_format: ''
  default: now
- name: toc
  type: boolean
  label: Show Table of Contents
  default: true
  description: Displayed on the right-hand side of the page
- name: tags
  type: tag_list
  default: []
  label: Tags
  description: "#tags shown at the bottom"
- name: categories
  type: tag_list
  default: []
  label: Categories
- name: series
  type: tag_list
  default: []
  label: Series
  description: "<em>i.e. for Part 1 and Part 2 posts</em>"
pages:
- site/content/posts/20211025-progress.md
- site/content/posts/20211026-progress.md
- site/content/posts/20211029-progress.md
- site/content/posts/20211030-progress.md
- site/content/posts/20220302-progress.md
- site/content/posts/capturing-network-activity-securely.md
- site/content/posts/capturing-packets-on-android.md
- site/content/posts/commentree.md
- site/content/posts/device-actions.md
- site/content/posts/etc-passwd.md
- site/content/posts/etc-shadow.md
- site/content/posts/frida-objection-https-without-mitm.md
- site/content/posts/htop-during-factory.md
- site/content/posts/i-am-root.md
- site/content/posts/main-view-checks.md
- site/content/posts/mmcblk0p7-var-log-apt-history.log.md
- site/content/posts/mmcblk0p7.md
- site/content/posts/points-of-contact.md
- site/content/posts/polarproxy.md
- site/content/posts/post-login-actions.md
- site/content/posts/project-focus.md
- site/content/posts/recovery-mode.md
- site/content/posts/report-a-preparation.md
- site/content/posts/roborock-s6-teardown.md
- site/content/posts/seminar-a-preparation.md
- site/content/posts/state-of-the-art.md
- site/content/posts/system-imaging.md
- site/content/posts/thesis-tasks.md
- site/content/posts/xiaomi-cyber-security-baseline-for-consumer-internet-of-things.md
