---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Post title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: date
  type: datetime
  label: Publish Date
  description: ''
  config:
    required: true
    date_format: ''
    time_format: 
    display_utc: false
    export_format: ''
  default: now
- name: toc
  type: boolean
  label: Show Table of Contents
  default: true
  description: Displayed on the right-hand side of the page
- name: tags
  type: tag_list
  default: []
  label: Tags
  description: "#tags shown at the bottom"
- name: categories
  type: tag_list
  default: []
  label: Categories
- name: series
  type: tag_list
  default: []
  label: Series
  description: "<em>i.e. for Part 1 and Part 2 posts</em>"
pages:
- site/content/posts/05-07-2022-further-points-of-contact.md
- site/content/posts/13-07-2022-progress-update.md
- site/content/posts/20211025-progress.md
- site/content/posts/20211026-progress.md
- site/content/posts/20211029-progress.md
- site/content/posts/20211030-progress.md
- site/content/posts/20220302-progress.md
- site/content/posts/achieving-upgrade-persistence.md
- site/content/posts/activity-traces.md
- site/content/posts/assessment-scope-diagram.md
- site/content/posts/boot-persistence.md
- site/content/posts/bootring.md
- site/content/posts/but-can-we-photorec.md
- site/content/posts/capture-log.md
- site/content/posts/capturing-network-activity-securely.md
- site/content/posts/capturing-packets-on-android.md
- site/content/posts/commentree.md
- site/content/posts/device-actions.md
- site/content/posts/devtest.conf.md
- site/content/posts/diff-inspection.md
- site/content/posts/disclosures.md
- site/content/posts/download-file-from-bash-without-wget-curl.md
- site/content/posts/etc-passwd.md
- site/content/posts/etc-shadow.md
- site/content/posts/file-system-comparison.md
- site/content/posts/files-in-device-that-are-missing-from-base.md
- site/content/posts/frida-objection-https-without-mitm.md
- site/content/posts/htop-during-factory.md
- site/content/posts/i-am-root.md
- site/content/posts/initialisation-pairing-process.md
- site/content/posts/ipv6-check.md
- site/content/posts/libc.md
- site/content/posts/main-view-checks.md
- site/content/posts/mmcblk0p7-var-log-apt-history.log.md
- site/content/posts/mmcblk0p7.md
- site/content/posts/mnt-data-rockrobo-rrlog-miio.log.md
- site/content/posts/mud.md
- site/content/posts/netstat.md
- site/content/posts/opt-roborock-md5-hashes.md
- site/content/posts/opt-rockrobo-rriot-rriot_tuya.md
- site/content/posts/ota-updates-blocked-as-of-late-2019.md
- site/content/posts/points-of-contact.md
- site/content/posts/polarproxy.md
- site/content/posts/post-login-actions.md
- site/content/posts/power-notes.md
- site/content/posts/pre-encryption-and-post-decryption-hooks.md
- site/content/posts/project-focus.md
- site/content/posts/psa-don-t-combine-program-arguments.md
- site/content/posts/readings.md
- site/content/posts/recovery-mode.md
- site/content/posts/report-a-preparation.md
- site/content/posts/roborock-s6-teardown.md
- site/content/posts/rrlogd.md
- site/content/posts/sankey-diagrams.md
- site/content/posts/sbin-rr_login.md
- site/content/posts/seminar-a-preparation.md
- site/content/posts/state-of-the-art.md
- site/content/posts/system-imaging.md
- site/content/posts/thesis-c-report-structure-notes.md
- site/content/posts/thesis-tasks.md
- site/content/posts/unit-reassembly-with-breakout-cables.md
- site/content/posts/updated-opt-rockrobo-rrlog-rrlogd.md
- site/content/posts/upgrade-notes.md
- site/content/posts/upgrade-reset-persistence.md
- site/content/posts/upgrade-upgrade-persistence.md
- site/content/posts/upgraded-accessing-the-shell.md
- site/content/posts/upgraded-boot-log.md
- site/content/posts/upgraded-netstat.md
- site/content/posts/upgraded-tcpdump-usage.md
- site/content/posts/upgraded-versioning-and-fingerprinting.md
- site/content/posts/usr-bin-qemu-arm-static.md
- site/content/posts/vinda.c.md
- site/content/posts/which-process-which-port-which-connection.md
- site/content/posts/xiaomi-cyber-security-baseline-for-consumer-internet-of-things.md
