---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site/content/presentations
  label: Presentation
  create: all
  match: "**/*"
- type: directory
  path: site/content/docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - doc
- type: directory
  path: site/content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - default
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year::month::day:-:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.68.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.68.3
