main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Docs
    url: /docs/
    weight: 3
  - name: Progress Log
    url: https://featherbear.cc/UNSW-CSE-Thesis/tldr/
    weight: 4
    
