main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Docs
    url: /docs/
    weight: 3
  - name: Progress Log
    url: /tldr/
    weight: 4
  - name: Thesis (PDF)
    url: /docs/report/thesis-smart-vacuum-cleaners-z5206677.pdf
    weight: 4
