name: github pages

on:
  push:
    branches:
    - master
    paths:
    - 'site/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          presentations:
            - 'site/content/presentations/**'
          tldr:
            - 'site/tldr/**'

    # For each file, add references to that page (so it's visible per website page)        
    - name: Update citations for Report A
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb -O /tmp/pandoc.deb
        sudo dpkg -i /tmp/pandoc.deb
        echo Citing entries for report A...
        ls -1 *.md | grep "^[^_]" | xargs -L1 -I {}  sh -c 'echo "\n\n## References\n\n" >> {}; pandoc {} -t gfm --citeproc --bibliography bib.bib --csl ref_format.cls -s -o {}'
      working-directory: ./site/content/docs/report-a

    # For each file, add references to that page (so it's visible per website page)
    - name: Update citations for Report C
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb -O /tmp/pandoc.deb
        sudo dpkg -i /tmp/pandoc.deb
        echo Citing entries for report C...
        ls -1 *.md | grep "^[^_]" | xargs -L1 -I {}  sh -c 'echo "\n\n## References\n\n" >> {}; pandoc {} -t gfm --citeproc --bibliography bib.bib --csl ref_format.cls -s -o {}'
      working-directory: ./site/content/docs/report-c

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.88.1'
        extended: true

    - name: Build Hugo site
      run: hugo --gc --minify --cleanDestinationDir -s site -d public

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build TLDR site
      if: steps.changes.outputs.tldr == 'true'
      run: |
        npm install
        npm run build
        cp -R public ../public/tldr
      working-directory: ./site/tldr

    - name: Build presentations as PDF
      if: steps.changes.outputs.presentations == 'true'
      run: |
        npm --prefix ./site/scripts install
        npm --prefix ./site/scripts run buildPDF

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        keep_files: true
        public_branch: gh-pages
        publish_dir: ./site/public
