name: github pages

on:
  push:
    branches:
    - master
    paths:
    - 'site/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.88.1'
        extended: true

    - name: Build Hugo site
      run: hugo --gc --minify --cleanDestinationDir -s site -d public

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build TLDR site
      run: |
        npm install
        npm run build
        cp -R public ../public/tldr
      working-directory: ./site/tldr

    - name: Build presentations as PDF
      run: |
        npm --prefix ./site/scripts install
        npm --prefix ./site/scripts run buildPDF

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site/public
